version: '3.7'

services:
  php-fpm:
    build:
      context: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/app/public:/var/www

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./docker/app/public:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log/nginx
    depends_on:
      - php-fpm
    ports:
      - "80:5050"

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=StrongPassword
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=password
    volumes:
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      -  ./data/:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db_data:
